[options]
admin_passwd = admin123
db_host = db_openeducat
db_port = 5431
db_user = odoo
db_password = odoo
list_db = True
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
logfile = /var/lib/odoo/odoo.log
log_level = debug
proxy_mode = True
workers = 0
limit_memory_hard = 0
limit_memory_soft = 0
limit_time_cpu = 0
limit_time_real = 0
limit_time_real_cron = 0
longpolling_port = 8072
